"""Port the reference stylesheet into a scoped one.

Every rule is prefixed with .v2 so the handoff design and the current site can
coexist while the port is in progress. The cases that cannot simply be
prefixed:

  :root            -> .v2            (tokens inherit, so the page root is fine)
  html, body       -> .v2            (the page root plays both parts)
  *, *::before...  -> .v2 *, ...     (scoped reset, not a global one)
  @keyframes       -> left alone, but renamed so they cannot collide with the
                      sixteen the current site already declares
  @media           -> recursed into

Keyframe names are prefixed too, and every animation: / animation-name:
reference is rewritten to match.
"""

import io
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

SRC = "reference/index.html"
OUT = "src/styles/v2-ported.css"
PREFIX = ".v2"
KF_PREFIX = "v2-"

css = re.search(r"<style>(.*?)</style>", io.open(SRC, encoding="utf-8").read(), re.S).group(1)

kf_names = sorted(set(re.findall(r"@keyframes\s+([A-Za-z0-9_-]+)", css)))


def scope_selector(sel: str) -> str:
    parts = [p.strip() for p in sel.split(",")]
    out = []
    for p in parts:
        if not p:
            continue
        if p == ":root" or p in ("html", "body", "html,body"):
            out.append(PREFIX)
        elif p.startswith("*"):
            out.append(f"{PREFIX} {p}")
        elif p.startswith("@"):
            out.append(p)
        else:
            out.append(f"{PREFIX} {p}")
    # de-duplicate while keeping order (html,body both becoming .v2)
    seen, uniq = set(), []
    for o in out:
        if o not in seen:
            seen.add(o)
            uniq.append(o)
    return ", ".join(uniq)


def walk(block: str) -> str:
    """Rewrite one level of rules, recursing into @media."""
    res = []
    i = 0
    n = len(block)
    while i < n:
        brace = block.find("{", i)
        if brace == -1:
            res.append(block[i:])
            break
        head = block[i:brace].strip()
        # find the matching close brace
        depth = 0
        j = brace
        while j < n:
            if block[j] == "{":
                depth += 1
            elif block[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        body = block[brace + 1 : j]

        if head.startswith("@keyframes"):
            name = head.split()[1]
            res.append(f"@keyframes {KF_PREFIX}{name} {{{body}}}\n")
        elif head.startswith("@media"):
            res.append(f"{head} {{\n{walk(body)}}}\n")
        elif head.startswith("@"):
            res.append(f"{head} {{{body}}}\n")
        else:
            res.append(f"{scope_selector(head)} {{{body}}}\n")
        i = j + 1
    return "".join(res)


ported = walk(css)

# rename every keyframe reference so the scoped copies are the ones used
for name in kf_names:
    ported = re.sub(rf"(animation\s*:[^;{{}}]*?\b){re.escape(name)}\b", rf"\1{KF_PREFIX}{name}", ported)
    ported = re.sub(rf"(animation-name\s*:\s*){re.escape(name)}\b", rf"\1{KF_PREFIX}{name}", ported)

header = f"""/* ──────────────────────────────────────────────────────────────────────────
   V2 — ported from reference/index.html.

   GENERATED by scripts/port-reference-css.mjs. The reference is the visual
   source of truth per CLAUDE.md, so this is a mechanical port rather than a
   re-interpretation: every rule is the reference's, prefixed with .v2 so the
   handoff design and the site it replaces can coexist until the swap.

   Three things the prefix could not handle on its own:
     :root and html/body all become .v2, since the page root plays every part
     the universal reset is scoped, so it cannot reach the rest of the site
     all {len(kf_names)} keyframes are renamed with a v2- prefix, because the current
       site declares sixteen of its own and several names collide
   ────────────────────────────────────────────────────────────────────────── */

"""

io.open(OUT, "w", encoding="utf-8", newline="\n").write(header + ported)

print(f"wrote {OUT}")
print(f"  {len(ported)} chars, {ported.count('{')} rules")
print(f"  {len(kf_names)} keyframes renamed: {', '.join(kf_names[:8])}...")
unscoped = [
    m.group(1).strip()
    for m in re.finditer(r"(?m)^([^@\s][^{]*)\{", ported)
    if not m.group(1).strip().startswith(PREFIX)
]
print(f"  unscoped top-level selectors: {unscoped if unscoped else 'none'}")
